[build]
dockerfile = "./docker/linux-cross/Dockerfile"
pre-build = [
    "curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --profile minimal --default-toolchain stable",
    ". $HOME/.cargo/env",
    "cargo install --force --locked bindgen-cli && mv $HOME/.cargo/bin/bindgen /usr/bin",
    "rm -rf $HOME/.cargo"
]

[build.env]
passthrough = [
    "CARGO_NDK_MAJOR_VERSION",
    "RUST_BACKTRACE",
    "RUST_LOG"
]

# Common settings for all Android targets
[target.'cfg(target_os = "android")']
image = "ghcr.io/cross-rs/android:latest"
xargo = false

# Architecture-specific configurations
[target.aarch64-linux-android]
image = "ghcr.io/cross-rs/aarch64-linux-android:latest"

[target.armv7-linux-androideabi]
image = "ghcr.io/cross-rs/armv7-linux-androideabi:latest"

[target.i686-linux-android]
image = "ghcr.io/cross-rs/i686-linux-android:latest"

[target.x86_64-linux-android]
image = "ghcr.io/cross-rs/x86_64-linux-android:latest"

# Common linker arguments for Android targets
[target.'cfg(target_os = "android")'.env]
CARGO_TARGET_AARCH64_LINUX_ANDROID_LINKER = "aarch64-linux-android-clang"
CARGO_TARGET_ARMV7_LINUX_ANDROIDEABI_LINKER = "armv7a-linux-androideabi-clang"
CARGO_TARGET_I686_LINUX_ANDROID_LINKER = "i686-linux-android-clang"
CARGO_TARGET_X86_64_LINUX_ANDROID_LINKER = "x86_64-linux-android-clang"
CFLAGS = "-fPIC"

# MIPS targets are dropped to Tier 3
# https://github.com/rust-lang/compiler-team/issues/648
# FIXME: build-std with sequence is supported only on git
# [target.mips-unknown-linux-gnu]
# build-std = ["std", "panic_abort", "proc_macro"]
# [target.mips-unknown-linux-musl]
# build-std = ["std", "panic_abort", "proc_macro"]
# [target.mips64-unknown-linux-gnuabi64]
# build-std = ["std", "panic_abort", "proc_macro"]
# [target.mips64-unknown-linux-muslabi64]
# build-std = ["std", "panic_abort", "proc_macro"]
# [target.mips64el-unknown-linux-gnuabi64]
# build-std = ["std", "panic_abort", "proc_macro"]
# [target.mips64el-unknown-linux-muslabi64]
# build-std = ["std", "panic_abort", "proc_macro"]
# [target.mipsel-unknown-linux-gnu]
# build-std = ["std", "panic_abort", "proc_macro"]
# [target.mipsel-unknown-linux-musl]
# build-std = ["std", "panic_abort", "proc_macro"]

